### ISSUE TITLE
500错误

### ISSUE THREAD

**Issue by lpkfndn** [SeriaWei/ZKEACMS.Core#182]
win7下，用iis发布架设出现问题，所有插件不能访问，报500错误。查看错误日志，如下
----------------------------------------------------------------
Event Time: 2018/4/30 星期一 上午 7:50:28
Error Message:
System.Exception: Fail to create ZKEACMS,ZKEACMS.Common.Service.HtmlWidgetService instance. May be the plugin is not exists or not regist.
   at ZKEACMS.Widget.DefaultWidgetActivator.Create(WidgetBase widget) in F:\downloads\ZKEACMS.Core-master\ZKEACMS.Core-master\src\ZKEACMS\Widget\DefaultWidgetActivator.cs:line 44
   at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass14_0.<GetAllByPage>b__3(WidgetBase widget) in F:\downloads\ZKEACMS.Core-master\ZKEACMS.Core-master\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 84
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass14_0.<GetAllByPage>b__0(PageEntity p) in F:\downloads\ZKEACMS.Core-master\ZKEACMS.Core-master\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 84
   at ZKEACMS.Widget.WidgetBasePartService.<>c__DisplayClass14_0.<GetAllByPage>b__1(String key, String region) in F:\downloads\ZKEACMS.Core-master\ZKEACMS.Core-master\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 88
   at CacheManager.Core.BaseCacheManager`1.<>c__DisplayClass84_0.<GetOrAdd>b__0(String k, String r)
   at CacheManager.Core.BaseCacheManager`1.GetOrAddInternal(String key, String region, Func`3 valueFactory)
   at CacheManager.Core.BaseCacheManager`1.GetOrAdd(String key, String region, Func`3 valueFactory)
   at ZKEACMS.Widget.WidgetBasePartService.GetAllByPage(PageEntity page, Boolean formCache) in F:\downloads\ZKEACMS.Core-master\ZKEACMS.Core-master\src\ZKEACMS\Widget\WidgetBasePartService.cs:line 88
   at ZKEACMS.Filter.WidgetAttribute.OnActionExecuted(ActionExecutedContext filterContext) in F:\downloads\ZKEACMS.Core-master\ZKEACMS.Core-master\src\ZKEACMS\Filter\WidgetAttribute.cs:line 100
   at Microsoft.AspNetCore.Mvc.Filters.ActionFilterAttribute.<OnActionExecutionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeInnerFilterAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeNextResourceFilter>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeFilterPipelineAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.<InvokeAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.<Invoke>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
----------------------------------------------------------------

**Comment by lpkfndn** [comment]
![localhost_8020_admin_eventviewer_viewlog_2018-04-3](https://user-images.githubusercontent.com/4144321/39412402-68427998-4c4e-11e8-846e-7aec61fd259c.png)
![default](https://user-images.githubusercontent.com/4144321/39412403-6ac9b1ae-4c4e-11e8-9033-823a95988844.png)

**Comment by SeriaWei** [comment]
不要在VS里面直接发布，这里有发布的文档：
http://www.zkea.net/zkeacms/document/publish/core
