### ISSUE TITLE
刪除文章類別出現服務器錯誤

### ISSUE THREAD

**Issue by w805756054** [SeriaWei/ZKEACMS.Core#221]
**### 請求參數：**

__RequestVerificationToken | CfDJ8Fh-YKL01sNGtLuQZKKXmLxIGhheyWAjgf4UfyY6X-b7Aw6FLY3IJadRI2KSK2aZcQ4tWfB5mIg1t0Hcf9WaWHmqCdRRB329Pw7U_HnfI_XHQum2JyROHC-Dedl1hN3-V9GDmirDjSFBInqTik3RzFf3V2O-i6LqtS59gT58yIAQaYiohKSZLJMnUQ8rCkD5fQ
-- | --
ActionType | Delete
CreateBy | admin
CreatebyName | Ian+wong
CreateDate | 2018/9/4+12:10:49
Description |  
ID | 2
LastUpdateBy | admin
LastUpdateByName | Ian+wong
LastUpdateDate | 2018/9/4+12:19:03
ParentID | 0
Status | 1
Title | 網頁管理技巧
Url | tips

**### 日誌：**
```
----------------------------------------------------------------
Event Time: 2018/9/4 12:24:02
Error Message:
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
Headers:
Connection:Keep-Alive
Content-Type:application/x-www-form-urlencoded
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:Hm_lvt_2d1709941ce6d596977d8dc23ba5b5ff=1535078331,1535367906,1535689858; __atuvc=3%7C35; __unam=9c025eb-1657f887fad-73a619d2-436; crisp-client%2Fsession%2F94d5136d-907a-422d-9363-f52fa4269935=session_4838b1c2-d22d-4097-804c-69edd7bafafc; .AspNetCore.Antiforgery.ENTeOukrPic=CfDJ8Fh-YKL01sNGtLuQZKKXmLwzeurn0kRnp80MoOJo0NsHPNdoqAkw8hS3tFHaoM1kLVDBODC_dTh7G62WtCZQp9M34yGCtcqxTthxAUVNdbelUcM2ykXndguFr3-sy3pI9bX9srpFiyjYS8zs9I_-4A8; .AspNetCore.Antiforgery.b9mIXy_DCu8=CfDJ8Fh-YKL01sNGtLuQZKKXmLxkuP-dd9Rldg8Dmbf07rXayRDY6H9k2PfeYiDtxQlhylltFZ6eH0mKWY3gUKZ59vV5eyYLfgh84Rdz6UbqGCnk50RiHCYEDz5hCM_R3I3QSvg1ySLdXnAWv26vY9Id_ZI; .AspNetCore.CustomerAuthenticationScheme=CfDJ8Fh-YKL01sNGtLuQZKKXmLwjqWFLhW8jw1zSwXKQxF6eFWjTp-VMVhE3pOHdyZdTHjeSh4bl866uxq_7Sk3vN0ei4jPjkScx0J8xgc8N-9h_cXA0iJ9o0Obk5enKcV_zujMjmWEYacOk8El_jbZyHbQBnIap8N9PISbxpFwxWX_2N2wojbfn74iMXUdH8wBKSQ8XQlZlHdGzJW_mchSs6fSvHWEXVJHOPFEJrPp-J-VWPiFvKuWN7zLp5nbbGSg6rGTkgTVTqkM2w1nlfQvUJ8T797422bWlliKOdE0QgKhOvj_JUvs4hm956JHMguhi5-bSDVRc_h9i_aRWMQTTCAR5e6MejKtXf6J_LEsleJNIXu1WFkaisQ5A0ugIHXZpcO8EgUbdYGSeio_hG-pZE-0; Hm_lpvt_2d1709941ce6d596977d8dc23ba5b5ff=1535970752; __sharethis_cookie_test__=1; .AspNetCore.DefaultAuthenticationScheme=CfDJ8Fh-YKL01sNGtLuQZKKXmLzuTSiIIHLljDCOAS4MQtn-pvQ6jGgs-VXZ9fHw1Z8C20KfxuH6CUyXaxD0PapuO0Z7YIlww6X5Cb-YfJ_SUwMXTPohEmT-sPefzO0oUsaZkbny2pL0aL4bAqMOR-2O4QOdQNJBodh-nyiPF6vNxlyzUJ4EWODNeyTa6RMRp9MCNK5RC7n3UULliGP2mXrJgruzMN7lOImcKSLHfCcGG9CbQgpr9ayyux9mqBz8kAemtwC8wsg-b_gscCjfe3KbXAivKgaLY2PwEDcCIffgjDyoyrWrnnFUUEwMY3-Fvq_cQFFOxdDKpXR93LCWqKzFzCAjiXp8Zlnh9jlRYLnLlzVAplfsImsZgdNSLM5zD50o-A
Host:www.start.hk
Referer:https://www.start.hk/admin/ArticleType/Edit/2
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Content-Length:511
Upgrade-Insecure-Requests:1
MS-ASPNETCORE-TOKEN:a35cc4c7-b447-426b-a38c-7b9ef5a89327
X-Original-Proto:http
X-Original-For:127.0.0.1:49711
/admin/ArticleType/Edit/2
----------------------------------------------------------------
```
```
----------------------------------------------------------------
Event Time: 2018/9/4 12:24:02
Error Message:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
Headers:
Connection:Keep-Alive
Content-Type:application/x-www-form-urlencoded
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:Hm_lvt_2d1709941ce6d596977d8dc23ba5b5ff=1535078331,1535367906,1535689858; __atuvc=3%7C35; __unam=9c025eb-1657f887fad-73a619d2-436; crisp-client%2Fsession%2F94d5136d-907a-422d-9363-f52fa4269935=session_4838b1c2-d22d-4097-804c-69edd7bafafc; .AspNetCore.Antiforgery.ENTeOukrPic=CfDJ8Fh-YKL01sNGtLuQZKKXmLwzeurn0kRnp80MoOJo0NsHPNdoqAkw8hS3tFHaoM1kLVDBODC_dTh7G62WtCZQp9M34yGCtcqxTthxAUVNdbelUcM2ykXndguFr3-sy3pI9bX9srpFiyjYS8zs9I_-4A8; .AspNetCore.Antiforgery.b9mIXy_DCu8=CfDJ8Fh-YKL01sNGtLuQZKKXmLxkuP-dd9Rldg8Dmbf07rXayRDY6H9k2PfeYiDtxQlhylltFZ6eH0mKWY3gUKZ59vV5eyYLfgh84Rdz6UbqGCnk50RiHCYEDz5hCM_R3I3QSvg1ySLdXnAWv26vY9Id_ZI; .AspNetCore.CustomerAuthenticationScheme=CfDJ8Fh-YKL01sNGtLuQZKKXmLwjqWFLhW8jw1zSwXKQxF6eFWjTp-VMVhE3pOHdyZdTHjeSh4bl866uxq_7Sk3vN0ei4jPjkScx0J8xgc8N-9h_cXA0iJ9o0Obk5enKcV_zujMjmWEYacOk8El_jbZyHbQBnIap8N9PISbxpFwxWX_2N2wojbfn74iMXUdH8wBKSQ8XQlZlHdGzJW_mchSs6fSvHWEXVJHOPFEJrPp-J-VWPiFvKuWN7zLp5nbbGSg6rGTkgTVTqkM2w1nlfQvUJ8T797422bWlliKOdE0QgKhOvj_JUvs4hm956JHMguhi5-bSDVRc_h9i_aRWMQTTCAR5e6MejKtXf6J_LEsleJNIXu1WFkaisQ5A0ugIHXZpcO8EgUbdYGSeio_hG-pZE-0; Hm_lpvt_2d1709941ce6d596977d8dc23ba5b5ff=1535970752; __sharethis_cookie_test__=1; .AspNetCore.DefaultAuthenticationScheme=CfDJ8Fh-YKL01sNGtLuQZKKXmLzuTSiIIHLljDCOAS4MQtn-pvQ6jGgs-VXZ9fHw1Z8C20KfxuH6CUyXaxD0PapuO0Z7YIlww6X5Cb-YfJ_SUwMXTPohEmT-sPefzO0oUsaZkbny2pL0aL4bAqMOR-2O4QOdQNJBodh-nyiPF6vNxlyzUJ4EWODNeyTa6RMRp9MCNK5RC7n3UULliGP2mXrJgruzMN7lOImcKSLHfCcGG9CbQgpr9ayyux9mqBz8kAemtwC8wsg-b_gscCjfe3KbXAivKgaLY2PwEDcCIffgjDyoyrWrnnFUUEwMY3-Fvq_cQFFOxdDKpXR93LCWqKzFzCAjiXp8Zlnh9jlRYLnLlzVAplfsImsZgdNSLM5zD50o-A
Host:www.start.hk
Referer:https://www.start.hk/admin/ArticleType/Edit/2
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Content-Length:511
Upgrade-Insecure-Requests:1
MS-ASPNETCORE-TOKEN:a35cc4c7-b447-426b-a38c-7b9ef5a89327
X-Original-Proto:http
X-Original-For:127.0.0.1:49711
/admin/ArticleType/Edit/2
----------------------------------------------------------------
```
```
----------------------------------------------------------------
Event Time: 2018/9/4 12:24:02
Error Message:
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while updating the entries. See the inner exception for details. ---> Microsoft.Data.Sqlite.SqliteException: SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Easy.RepositoryPattern.ServiceBase`1.SaveChanges()
   at Easy.Mvc.Controllers.BasicController`3.Edit(TEntity entity)
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)
Headers:
Connection:Keep-Alive
Content-Type:application/x-www-form-urlencoded
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding:gzip, deflate, br
Accept-Language:zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
Cookie:Hm_lvt_2d1709941ce6d596977d8dc23ba5b5ff=1535078331,1535367906,1535689858; __atuvc=3%7C35; __unam=9c025eb-1657f887fad-73a619d2-436; crisp-client%2Fsession%2F94d5136d-907a-422d-9363-f52fa4269935=session_4838b1c2-d22d-4097-804c-69edd7bafafc; .AspNetCore.Antiforgery.ENTeOukrPic=CfDJ8Fh-YKL01sNGtLuQZKKXmLwzeurn0kRnp80MoOJo0NsHPNdoqAkw8hS3tFHaoM1kLVDBODC_dTh7G62WtCZQp9M34yGCtcqxTthxAUVNdbelUcM2ykXndguFr3-sy3pI9bX9srpFiyjYS8zs9I_-4A8; .AspNetCore.Antiforgery.b9mIXy_DCu8=CfDJ8Fh-YKL01sNGtLuQZKKXmLxkuP-dd9Rldg8Dmbf07rXayRDY6H9k2PfeYiDtxQlhylltFZ6eH0mKWY3gUKZ59vV5eyYLfgh84Rdz6UbqGCnk50RiHCYEDz5hCM_R3I3QSvg1ySLdXnAWv26vY9Id_ZI; .AspNetCore.CustomerAuthenticationScheme=CfDJ8Fh-YKL01sNGtLuQZKKXmLwjqWFLhW8jw1zSwXKQxF6eFWjTp-VMVhE3pOHdyZdTHjeSh4bl866uxq_7Sk3vN0ei4jPjkScx0J8xgc8N-9h_cXA0iJ9o0Obk5enKcV_zujMjmWEYacOk8El_jbZyHbQBnIap8N9PISbxpFwxWX_2N2wojbfn74iMXUdH8wBKSQ8XQlZlHdGzJW_mchSs6fSvHWEXVJHOPFEJrPp-J-VWPiFvKuWN7zLp5nbbGSg6rGTkgTVTqkM2w1nlfQvUJ8T797422bWlliKOdE0QgKhOvj_JUvs4hm956JHMguhi5-bSDVRc_h9i_aRWMQTTCAR5e6MejKtXf6J_LEsleJNIXu1WFkaisQ5A0ugIHXZpcO8EgUbdYGSeio_hG-pZE-0; Hm_lpvt_2d1709941ce6d596977d8dc23ba5b5ff=1535970752; __sharethis_cookie_test__=1; .AspNetCore.DefaultAuthenticationScheme=CfDJ8Fh-YKL01sNGtLuQZKKXmLzuTSiIIHLljDCOAS4MQtn-pvQ6jGgs-VXZ9fHw1Z8C20KfxuH6CUyXaxD0PapuO0Z7YIlww6X5Cb-YfJ_SUwMXTPohEmT-sPefzO0oUsaZkbny2pL0aL4bAqMOR-2O4QOdQNJBodh-nyiPF6vNxlyzUJ4EWODNeyTa6RMRp9MCNK5RC7n3UULliGP2mXrJgruzMN7lOImcKSLHfCcGG9CbQgpr9ayyux9mqBz8kAemtwC8wsg-b_gscCjfe3KbXAivKgaLY2PwEDcCIffgjDyoyrWrnnFUUEwMY3-Fvq_cQFFOxdDKpXR93LCWqKzFzCAjiXp8Zlnh9jlRYLnLlzVAplfsImsZgdNSLM5zD50o-A
Host:www.start.hk
Referer:https://www.start.hk/admin/ArticleType/Edit/2
User-Agent:Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0
Content-Length:511
Upgrade-Insecure-Requests:1
MS-ASPNETCORE-TOKEN:a35cc4c7-b447-426b-a38c-7b9ef5a89327
X-Original-Proto:http
X-Original-For:127.0.0.1:49711
/admin/ArticleType/Edit/2
----------------------------------------------------------------
```

**Comment by w805756054** [comment]
其他都可以成功刪除，就這個有問題

**Comment by SeriaWei** [comment]
这是因为这个类别在页面里面被引用了

**Comment by SeriaWei** [comment]
删除外键约束即可：
```
ALTER TABLE [dbo].[ArticleTypeWidget] DROP CONSTRAINT [FK_ArticleTypeWidget_ArticleType]
```
```
ALTER TABLE [dbo].[ProductCategoryWidget] DROP CONSTRAINT [FK_ProductCategoryWidget_ProductCategory]
```
