### ISSUE TITLE
数据库操作出错

### ISSUE THREAD

**Issue by tangdf** [SeriaWei/ZKEACMS.Core#75]
这是堆栈信息：

> System.Data.SqlClient.SqlException (0x80131904): 不允许启动新事务，因为有其他线程正在该会话中运行。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.TdsParser.Run(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj)
   at System.Data.SqlClient.TdsParser.TdsExecuteTransactionManagerRequest(Byte[] buffer, TransactionManagerRequestType request, String transactionName, TransactionManagerIsolationLevel isoLevel, Int32 timeout, SqlInternalTransaction transaction, TdsParserStateObject stateObj)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransactionYukon(TransactionRequest transactionRequest, String transactionName, IsolationLevel iso, SqlInternalTransaction internalTransaction)
   at System.Data.SqlClient.SqlInternalConnectionTds.ExecuteTransaction(TransactionRequest transactionRequest, String name, IsolationLevel iso, SqlInternalTransaction internalTransaction)
   at System.Data.SqlClient.SqlInternalConnection.BeginSqlTransaction(IsolationLevel iso, String transactionName, Boolean shouldReconnect)
   at System.Data.SqlClient.SqlConnection.BeginTransaction(IsolationLevel iso, String transactionName)
   at System.Data.SqlClient.SqlConnection.BeginDbTransaction(IsolationLevel isolationLevel)
   at System.Data.Common.DbConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction(IsolationLevel isolationLevel)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransaction()
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(Tuple`2 parameters)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, TState state, Func`2 operation)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IReadOnlyList`1 entries)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()
   at Easy.RepositoryPattern.ServiceBase`2.Update(T item, Boolean saveImmediately) in G:\TDDownload\ZKEACMS.Core-2.0\ZKEACMS.Core-2.0\src\EasyFrameWork\RepositoryPattern\ServiceBase.cs:line 159
   at ZKEACMS.Page.PageService.Update(PageEntity item, Boolean saveImmediately) in G:\TDDownload\ZKEACMS.Core-2.0\ZKEACMS.Core-2.0\src\ZKEACMS\Page\PageService.cs:line 57
   at ZKEACMS.Page.PageService.<Move>b__13_0(PageEntity m) in G:\TDDownload\ZKEACMS.Core-2.0\ZKEACMS.Core-2.0\src\ZKEACMS\Page\PageService.cs:line 204
   at Easy.Extend.ExtIEnumerable.Each[T](IEnumerable`1 source, Action`1 fun) in G:\TDDownload\ZKEACMS.Core-2.0\ZKEACMS.Core-2.0\src\EasyFrameWork\Extend\ExtIEnumerable.cs:line 15
   at ZKEACMS.Page.PageService.Move(String id, Int32 position, Int32 oldPosition) in G:\TDDownload\ZKEACMS.Core-2.0\ZKEACMS.Core-2.0\src\ZKEACMS\Page\PageService.cs:line 201
   at ZKEACMS.Controllers.PageController.MovePage(String id, Int32 position, Int32 oldPosition) in G:\TDDownload\ZKEACMS.Core-2.0\ZKEACMS.Core-2.0\src\ZKEACMS\Controllers\PageController.cs:line 210
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__12.MoveNext()
ClientConnectionId:7a312abb-f653-4942-ae60-2e5fba91118e
Error Number:3988,State:1,Class:16

**Comment by SeriaWei** [comment]
是不是你的连接字符串不对？需要 MultipleActiveResultSets=true;

**Comment by tangdf** [comment]
下面是`appsettings.json`的配置：

> {
  "ConnectionStrings": {
    "DefaultConnection": "Server=192.168.10.46\\SQLSERVER2016;Database=ZKEACMS_Core;User Id=sa;Password=sa;MultipleActiveResultSets=true;",
    "Sqlite": "",
    "MySql": ""
  },
  "ApplicationInsights": {
    "InstrumentationKey": ""
  },
  "Logging": {
    "IncludeScopes": false,
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "CDN": {
    "Enable": false,
    "Url": "http://cdn.zkeasoft.com/core"
  },
  "Culture": {
    "Code": "zh-CN"
  }
}

**Comment by SeriaWei** [comment]
那就有点奇怪了。

**Comment by tangdf** [comment]
这个问题是与我提的另一个问题 #74 相关的，`IService<T>`接口的`Get`方法返回的是`IEnumerable<T>`类型，将返回的结果做`foreach`的时候，Entity Framework是通过`IDataReader`来读取数据的，如果循环未完成之前，数据库链接是不会断开的，此时调用`DbContext`的`SaveChange`方法，需要开启新的事务，就会报错。
在调用`IService<T>`接口的`Get`方法后，再调用`ToList`方法，是不会报错的。
这个错误在博客园上有很多人提供了解决办法。

**Comment by tangdf** [comment]
我还是建议将`IService<T>`接口的`Get`方法返回的类型改为'List<>'类型。

**Comment by SeriaWei** [comment]
其实我之前有考虑过改个。之前在sqlite数据库也有出现过类似的情况，当时我也是直接 ToList 简单解决了。是应该改成IList，这样可以防止一些不必要的错误。

**Comment by SeriaWei** [comment]
修改已经提交到了 develop 分支。
